[project]
name = "redirect-sha256"
authors = ["Developer Name <developer@example.com>"]
description = "SHA256-based goal tracking smart contract with secure verification"
telemetry = false
requirements = []

[contracts.redirect-tracker]
path = "contracts/redirect-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
